import type { TypesenseCollectionConfig } from "./types.ts";

/** Typesense collection config for bookings. */
export const bookings: TypesenseCollectionConfig = {
  alias: "bookings",
  version: 3,
  firestoreCollection: "bookings",
  collectionName: "bookings_v3",
  enabled: false,
  schema: {
    name: "bookings_v3",
    enable_nested_fields: true,
    fields: [
      { name: "uid", type: "string", sort: true, facet: false },
      { name: "uid_product", type: "string", facet: false },
      { name: "uid_order", type: "string", facet: false },
      { name: "number", type: "int64", sort: true, index: true, facet: false },
      { name: "number_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "crms_id", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "crms_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "crms_product_id", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "crms_product_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "status", type: "string", facet: true },
      { name: "type", type: "string", facet: true },
      { name: "name", type: "string", sort: true, stem: true },
      { name: "subject", type: "string", sort: true, stem: true, optional: true },
      { name: "organization", type: "object" },
      { name: "organization.uid", type: "string", facet: false, optional: true },
      { name: "organization.name", type: "string", sort: true, stem: true, facet: false },
      { name: "organization.crms_id", type: "int64", optional: true },
      { name: "organization.crms_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "breakdown", type: "object" },
      { name: "breakdown.out", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.prepped", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.returned", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.quoted", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.reserved", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.lost", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.damaged", type: "int32", sort: true, index: true, facet: false },
      { name: "quantity", type: "int32", sort: true, index: true, facet: false },
      { name: "shortage", type: "int32", sort: true, index: true, facet: false, optional: true },
      { name: "total_price", type: "float", sort: true, index: true, facet: false, optional: true },
      { name: "unit_price", type: "float", sort: true, index: true, facet: false, optional: true },
      { name: "dates", type: "object" },
      { name: "dates.start_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "dates.end_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "dates.charge_start_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "dates.charge_end_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "destinations", type: "object", optional: true },
      { name: "destinations.delivery", type: "object", optional: true },
      { name: "destinations.delivery.uid", type: "string", optional: true },
      { name: "destinations.delivery.address", type: "object", optional: true },
      { name: "destinations.delivery.address.full", type: "string", stem: true, optional: true },
      { name: "destinations.delivery.address.city", type: "string", facet: true, optional: true },
      { name: "destinations.delivery.address.region", type: "string", facet: true, optional: true },
      { name: "destinations.collection", type: "object", optional: true },
      { name: "destinations.collection.uid", type: "string", optional: true },
      { name: "destinations.collection.address", type: "object", optional: true },
      { name: "destinations.collection.address.full", type: "string", stem: true, optional: true },
      { name: "destinations.collection.address.city", type: "string", facet: true, optional: true },
      { name: "destinations.collection.address.region", type: "string", facet: true, optional: true },
      { name: "stores", type: "object[]", optional: true },
      { name: "stores.uid_store", type: "string[]", facet: false, optional: true },
      { name: "stores.name", type: "string[]", stem: true, optional: true },
      { name: "stores.quantity", type: "int32[]", optional: true },
      { name: "uid_destination_delivery", type: "string", facet: false, optional: true },
      { name: "uid_destination_collection", type: "string", facet: false, optional: true },
      { name: "created_at", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "updated_at", type: "int64", sort: true, index: true, facet: false },
    ],
    default_sorting_field: "updated_at",
  },
  synonyms: [],
  displayDefaults: {
    columns: ["number", "name", "status", "organization.name", "quantity"],
    filters: { status: [] },
    sort: { column: "number", direction: "desc" },
    group: null,
    facet: [],
  },
};
