import type { TypesenseCollectionConfig } from "./types.ts";

/** Typesense collection config for contacts. */
export const contacts: TypesenseCollectionConfig = {
  alias: "contacts",
  version: 8,
  firestoreCollection: "contacts",
  collectionName: "contacts_v8",
  schema: {
    name: "contacts_v8",
    enable_nested_fields: true,
    token_separators: ["(", ")", "-", "+", " "],
    fields: [
      { name: "uid", type: "string", sort: true, facet: false },
      { name: "name", type: "string", sort: true, stem: true, facet: false },
      { name: "first_name", type: "string", sort: true, stem: true, facet: false },
      { name: "middle_name", type: "string", stem: true, facet: false, optional: true },
      { name: "last_name", type: "string", sort: true, stem: true, facet: false, optional: true },
      { name: "pronunciation", type: "string", stem: true, facet: false, optional: true },
      { name: "crms_id", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "crms_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "emails", type: "string[]", stem: true },
      { name: "phones", type: "string[]" },
      { name: "organizations", type: "object[]", optional: true },
      { name: "organizations.uid", type: "string[]", facet: false, optional: true },
      { name: "organizations.name", type: "string[]", stem: true, optional: true },
      { name: "created_by", type: "object", optional: true },
      { name: "created_by.uid", type: "string", facet: true, optional: true },
      { name: "created_by.name", type: "string", sort: true, stem: true, facet: true, optional: true },
      { name: "updated_by", type: "object", optional: true },
      { name: "updated_by.uid", type: "string", facet: true, optional: true },
      { name: "updated_by.name", type: "string", sort: true, stem: true, facet: true, optional: true },
      { name: "created_at", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "updated_at", type: "int64", sort: true, index: true, facet: false },
    ],
    default_sorting_field: "name",
  },
  synonyms: [],
  displayDefaults: {
    columns: ["name", "emails", "phones", "organizations.name"],
    filters: {},
    sort: { column: "name", direction: "asc" },
    group: null,
    facet: [],
  },
};
