import type { TypesenseCollectionConfig } from "./types.ts";

export const destinations: TypesenseCollectionConfig = {
  alias: "destinations",
  version: 3,
  firestoreCollection: "destinations",
  collectionName: "destinations_v3",
  schema: {
    name: "destinations_v3",
    enable_nested_fields: true,
    fields: [
      { name: "uid", type: "string", sort: true, facet: false },
      { name: "mapbox_ids", type: "string[]", facet: true },
      { name: "address", type: "object", optional: true },
      { name: "address.full", type: "string", sort: true, stem: true, optional: true },
      { name: "address.name", type: "string", stem: true, optional: true },
      { name: "address.city", type: "string", facet: true, optional: true },
      { name: "address.region", type: "string", facet: true, optional: true },
      { name: "address.street", type: "string", stem: true, optional: true },
      { name: "address.country_name", type: "string", facet: true, optional: true },
      { name: "address.address_coordinates", type: "object", optional: true },
      { name: "address.user_coordinates", type: "object", optional: true },
      { name: "organizations", type: "object[]", optional: true },
      { name: "organizations.uid", type: "string[]", facet: false, optional: true },
      { name: "organizations.name", type: "string[]", stem: true, optional: true },
      { name: "products", type: "object[]", optional: true },
      { name: "products.uid", type: "string[]", facet: false, optional: true },
      { name: "products.name", type: "string[]", stem: true, optional: true },
      { name: "contacts", type: "object[]", optional: true },
      { name: "contacts.uid", type: "string[]", facet: false, optional: true },
      { name: "contacts.name", type: "string[]", stem: true, optional: true },
      { name: "updated_at", type: "int64", sort: true, index: true, facet: false },
    ],
    default_sorting_field: "updated_at",
  },
};
