import type { TypesenseCollectionConfig } from "./types.ts";
import { typesenseAddressFields } from "./types.ts";

/** Typesense collection config for invoices. */
export const invoices: TypesenseCollectionConfig = {
  alias: "invoices",
  version: 6,
  firestoreCollection: "invoices",
  collectionName: "invoices_v6",
  schema: {
    name: "invoices_v6",
    enable_nested_fields: true,
    fields: [
      { name: "uid", type: "string", sort: true, facet: false },
      { name: "number", type: "int64", sort: true, index: true, facet: false },
      { name: "number_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "status", type: "string", facet: true },
      { name: "tax_profile", type: "string", facet: true },
      { name: "uid_orders", type: "string[]", facet: false, optional: true },
      { name: "subject", type: "string", stem: true, sort: true, optional: true },
      { name: "reference", type: "string", stem: true, sort: true, optional: true },
      { name: "external_notes", type: "string", stem: true, optional: true },
      { name: "internal_notes", type: "string", stem: true, optional: true },
      { name: "organization", type: "object" },
      { name: "organization.uid", type: "string", facet: false, optional: true },
      { name: "organization.name", type: "string", sort: true, stem: true, facet: false },
      { name: "organization.crms_id", type: "int64", optional: true },
      { name: "organization.crms_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "organization.tax_profile", type: "string", facet: true, optional: true },
      { name: "organization.xero_id", type: "string", optional: true },
      ...typesenseAddressFields("organization.billing_address"),
      { name: "items", type: "object[]", optional: true },
      { name: "items.uid", type: "string[]", facet: false, optional: true },
      { name: "items.name", type: "string[]", stem: true, optional: true },
      { name: "items.quantity", type: "int32[]", optional: true },
      { name: "items.type", type: "string[]", facet: true, optional: true },
      { name: "totals", type: "object", optional: true },
      { name: "totals.total", type: "float", sort: true, optional: true },
      { name: "totals.total_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "totals.amount_paid", type: "float", sort: true, optional: true },
      { name: "totals.amount_paid_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "totals.amount_due", type: "float", sort: true, optional: true },
      { name: "totals.amount_due_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "crms_id", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "crms_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "crms_opportunity_ids", type: "int64[]", optional: true },
      { name: "xero_id", type: "string", optional: true },
      { name: "updated_by", type: "string", facet: false, optional: true },
      { name: "date_fs", type: "int64", sort: true, index: true, facet: false },
      { name: "due_date_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "created_at", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "updated_at", type: "int64", sort: true, index: true, facet: false, optional: true },
    ],
    default_sorting_field: "number",
  },
  synonyms: [],
  displayDefaults: {
    columns: ["number", "organization.name", "reference", "subject", "status"],
    filters: { status: [] },
    sort: { column: "number", direction: "desc" },
    group: null,
    facet: [],
  },
};
