import type { TypesenseCollectionConfig } from "./types.ts";

export const orders: TypesenseCollectionConfig = {
  alias: "orders",
  version: 11,
  firestoreCollection: "orders",
  collectionName: "orders_v11",
  schema: {
    name: "orders_v11",
    enable_nested_fields: true,
    fields: [
      { name: "uid", type: "string", sort: true, facet: false },
      { name: "number", type: "int64", sort: true, index: true, facet: false },
      { name: "number_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "crms_id", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "crms_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "status", type: "string", facet: true },
      { name: "tax_profile", type: "string", facet: true },
      { name: "customer_collecting", type: "bool", facet: true, optional: true },
      { name: "customer_returning", type: "bool", facet: true, optional: true },
      { name: "subject", type: "string", sort: true, stem: true, optional: true },
      { name: "reference", type: "string", stem: true, sort: true, optional: true },
      { name: "notes", type: "string", stem: true, optional: true },
      { name: "crms_status", type: "string", stem: true, optional: true },
      { name: "organization", type: "object" },
      { name: "organization.uid", type: "string", facet: false, optional: true },
      { name: "organization.name", type: "string", sort: true, stem: true, facet: false },
      { name: "organization.crms_id", type: "int64", optional: true },
      { name: "organization.crms_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "dates", type: "object" },
      { name: "dates.delivery_start_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "dates.delivery_end_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "dates.collection_start_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "dates.collection_end_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "dates.charge_start_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "dates.charge_end_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "destinations", type: "object[]" },
      { name: "destinations.delivery", type: "object[]", optional: true },
      { name: "destinations.delivery.address", type: "object[]", optional: true },
      { name: "destinations.delivery.address.full", type: "string[]", stem: true, optional: true },
      { name: "destinations.delivery.address.city", type: "string[]", facet: false, optional: true },
      { name: "destinations.delivery.address.region", type: "string[]", facet: false, optional: true },
      { name: "destinations.delivery.instructions", type: "string[]", stem: true, optional: true },
      { name: "destinations.delivery.contact", type: "object[]", optional: true },
      { name: "destinations.delivery.contact.uid", type: "string[]", facet: false, optional: true },
      { name: "destinations.delivery.contact.name", type: "string[]", stem: true, optional: true },
      { name: "destinations.collection", type: "object[]", optional: true },
      { name: "destinations.collection.address", type: "object[]", optional: true },
      { name: "destinations.collection.address.full", type: "string[]", stem: true, optional: true },
      { name: "destinations.collection.address.city", type: "string[]", facet: false, optional: true },
      { name: "destinations.collection.address.region", type: "string[]", facet: false, optional: true },
      { name: "destinations.collection.instructions", type: "string[]", stem: true, optional: true },
      { name: "destinations.collection.contact", type: "object[]", optional: true },
      { name: "destinations.collection.contact.uid", type: "string[]", facet: false, optional: true },
      { name: "destinations.collection.contact.name", type: "string[]", stem: true, optional: true },
      { name: "totals", type: "object" },
      { name: "totals.discount_amount", type: "float", optional: true },
      { name: "totals.subtotal", type: "float", optional: true },
      { name: "totals.taxes", type: "object", optional: true },
      { name: "totals.total", type: "float", sort: true, optional: true },
      { name: "items", type: "object[]", optional: true },
      { name: "items.uid", type: "string[]", facet: false, optional: true },
      { name: "items.name", type: "string[]", stem: true, optional: true },
      { name: "items.quantity", type: "int32[]", optional: true },
      { name: "items.type", type: "string[]", facet: true, optional: true },
      { name: "items.description", type: "string[]", stem: true, optional: true },
      { name: "items.stock_method", type: "string[]", facet: true, optional: true },
      { name: "items.inclusion_type", type: "string[]", optional: true },
      { name: "items.zero_priced", type: "bool[]", optional: true },
      { name: "items.uid_order", type: "string[]", optional: true },
      { name: "items.order_number", type: "int32[]", optional: true },
      { name: "items.uid_component_of", type: "string[]", optional: true },
      { name: "items.uid_delivery", type: "string[]", optional: true },
      { name: "items.uid_collection", type: "string[]", optional: true },
      { name: "items.total_price", type: "float[]", optional: true },
      { name: "items.price", type: "object[]", optional: true },
      { name: "items.price.base", type: "float[]", optional: true },
      { name: "items.price.subtotal", type: "float[]", optional: true },
      { name: "items.price.total", type: "float[]", optional: true },
      { name: "items.price.tax_amount", type: "float[]", optional: true },
      { name: "items.price.discount_amount", type: "float[]", optional: true },
      { name: "items.price.discount_percent", type: "float[]", optional: true },
      { name: "items.price.chargeable_days", type: "int32[]", optional: true },
      { name: "items.price.formula", type: "string[]", optional: true },
      { name: "items.price.tax_profile", type: "string[]", facet: true, optional: true },
      { name: "destinations.delivery.uid", type: "string[]", optional: true },
      { name: "destinations.collection.uid", type: "string[]", optional: true },
      { name: "created_at", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "updated_at", type: "int64", sort: true, index: true, facet: false },
    ],
    default_sorting_field: "number",
  },
  synonyms: [],
  displayDefaults: {
    columns: ["number", "organization.name", "subject", "status"],
    filters: { status: [] },
    sort: { column: "number", direction: "desc" },
    group: null,
    facet: [],
  },
};
