import type { TypesenseCollectionConfig } from "./types.ts";

export const organizations: TypesenseCollectionConfig = {
  alias: "organizations",
  version: 8,
  firestoreCollection: "organizations",
  collectionName: "organizations_v8",
  schema: {
    name: "organizations_v8",
    enable_nested_fields: true,
    token_separators: ["(", ")", "-", "+", " "],
    fields: [
      { name: "uid", type: "string", sort: true, facet: false },
      { name: "name", type: "string", sort: true, stem: true, facet: false },
      { name: "description", type: "string", stem: true, optional: true },
      { name: "crms_id", type: "int64", sort: true, index: true, facet: false },
      { name: "crms_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "xero_id", type: "string", facet: false, optional: true },
      { name: "tax_profile", type: "string", facet: true },
      { name: "emails", type: "string[]", stem: true, optional: true },
      { name: "phones", type: "string[]", optional: true },
      { name: "billing_address", type: "object" },
      { name: "billing_address.name", type: "string", stem: true, optional: true },
      { name: "billing_address.street", type: "string", stem: true, optional: true },
      { name: "billing_address.full", type: "string", stem: true, optional: true, sort: true },
      { name: "billing_address.street2", type: "string", stem: true, optional: true },
      { name: "billing_address.city", type: "string", facet: false, optional: true },
      { name: "billing_address.region", type: "string", facet: false, optional: true },
      { name: "billing_address.postcode", type: "string", facet: false, optional: true },
      { name: "billing_address.country_name", type: "string", facet: false, optional: true },
      { name: "billing_address.address_coordinates", type: "object", optional: true },
      { name: "billing_address.address_coordinates.latitude", type: "float", optional: true },
      { name: "billing_address.address_coordinates.longitude", type: "float", optional: true },
      { name: "billing_address.user_coordinates", type: "object", optional: true },
      { name: "billing_address.user_coordinates.latitude", type: "float", optional: true },
      { name: "billing_address.user_coordinates.longitude", type: "float", optional: true },
      { name: "contacts", type: "object[]" },
      { name: "contacts.uid", type: "string[]", facet: false, optional: true },
      { name: "contacts.name", type: "string[]", stem: true, facet: false, optional: true },
      { name: "contacts.roles", type: "string[]", facet: false, optional: true },
      { name: "updated_by", type: "string", facet: false, optional: true, sort: true },
      { name: "last_order", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "created_at", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "updated_at", type: "int64", sort: true, index: true, facet: false },
    ],
    default_sorting_field: "name",
  },
};
