import type { TypesenseCollectionConfig } from "./types.ts";

export const products: TypesenseCollectionConfig = {
  alias: "products",
  version: 10,
  firestoreCollection: "products",
  collectionName: "products_v10",
  schema: {
    name: "products_v10",
    enable_nested_fields: true,
    fields: [
      { name: "uid", type: "string", sort: true, facet: false },
      { name: "name", type: "string", sort: true, stem: true, facet: false },
      { name: "description", type: "string", stem: true, optional: true },
      { name: "tracking_category_name", type: "string", sort: true, stem: true, facet: false, optional: true },
      { name: "type", type: "string", facet: true, sort: true, stem: true },
      { name: "stock_method", type: "string", facet: true, sort: true, stem: true },
      { name: "active", type: "bool", sort: true, facet: true },
      { name: "component_only", type: "bool", sort: true, facet: true },
      { name: "eligible_delivery", type: "bool", sort: true, facet: true, optional: true },
      { name: "eligible_in_store_pickup", type: "bool", sort: true, facet: true, optional: true },
      { name: "eligible_shipping_ground", type: "bool", sort: true, facet: true, optional: true },
      { name: "eligible_shipping_air", type: "bool", sort: true, facet: true, optional: true },
      { name: "price", type: "object", optional: true },
      { name: "price.base", type: "float", optional: true },
      { name: "price.replacement", type: "float", optional: true },
      { name: "price.coa_revenue", type: "string", facet: true, optional: true },
      { name: "price.tax_profile", type: "string", facet: true, optional: true },
      { name: "price.formula", type: "string", facet: true, optional: true },
      { name: "price.discountable", type: "bool", facet: true, optional: true },
      { name: "webshop", type: "object", optional: true },
      { name: "webshop.available", type: "bool", facet: true, optional: true },
      { name: "webshop.description", type: "string", optional: true },
      { name: "alternates", type: "object[]", optional: true },
      { name: "alternates.uid", type: "string[]", facet: false, optional: true },
      { name: "alternates.name", type: "string[]", stem: true, optional: true },
      { name: "crms_id", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "crms_id_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "uid_tracking_category", type: "string", facet: true, optional: true },
      { name: "uid_linked_replacement", type: "string", optional: true },
      { name: "uid_linked_rental", type: "string", optional: true },
      { name: "xero_id", type: "string", optional: true },
      { name: "xero_tracking_option_id", type: "string", optional: true },
      { name: "crms_rate_id", type: "int64", optional: true },
      { name: "crms_linked_rental_id", type: "int64", optional: true },
      { name: "crms_linked_replacement_id", type: "int64", optional: true },
      { name: "crms_linked_replacement_rate_id", type: "int64", optional: true },
      { name: "shipping", type: "object", optional: true },
      { name: "shipping.weight", type: "int32", optional: true },
      { name: "shipping.height", type: "int32", optional: true },
      { name: "shipping.width", type: "int32", optional: true },
      { name: "shipping.length", type: "int32", optional: true },
      { name: "shipping.air_hazardous", type: "bool", facet: true, optional: true },
      { name: "shipping.air_un", type: "int32", optional: true },
      { name: "tags", type: "object[]", optional: true },
      { name: "tags.uid", type: "string[]", facet: true, optional: true },
      { name: "tags.name", type: "string[]", stem: true, facet: true, optional: true },
      { name: "components", type: "object[]", optional: true },
      { name: "components.uid", type: "string[]", optional: true },
      { name: "components.name", type: "string[]", optional: true },
      { name: "components.quantity", type: "float[]", optional: true },
      { name: "components.active", type: "bool[]", facet: true, optional: true },
      { name: "components.crms_id", type: "int64[]", optional: true },
      { name: "components.crms_accessory_id", type: "int64[]", optional: true },
      { name: "components.description", type: "string[]", optional: true },
      { name: "components.inclusion_type", type: "string[]", facet: true, optional: true },
      { name: "components.type", type: "string[]", facet: true, optional: true },
      { name: "components.zero_priced", type: "bool[]", facet: true, optional: true },
      { name: "components.price", type: "object[]", optional: true },
      { name: "components.price.base", type: "float[]", optional: true },
      { name: "components.price.replacement", type: "float[]", optional: true },
      { name: "components.price.coa_revenue", type: "string[]", facet: true, optional: true },
      { name: "components.price.tax_profile", type: "string[]", optional: true },
      { name: "components.price.formula", type: "string[]", facet: true, optional: true },
      { name: "components.price.discountable", type: "bool[]", facet: true, optional: true },
      { name: "component_of", type: "object[]", optional: true },
      { name: "component_of.uid", type: "string[]", optional: true },
      { name: "component_of.name", type: "string[]", optional: true },
      { name: "component_of.quantity", type: "float[]", optional: true },
      { name: "component_of.active", type: "bool[]", facet: true, optional: true },
      { name: "component_of.crms_id", type: "int64[]", optional: true },
      { name: "component_of.crms_accessory_id", type: "int64[]", optional: true },
      { name: "component_of.description", type: "string[]", optional: true },
      { name: "component_of.inclusion_type", type: "string[]", facet: true, optional: true },
      { name: "component_of.type", type: "string[]", facet: true, optional: true },
      { name: "component_of.zero_priced", type: "bool[]", facet: true, optional: true },
      { name: "component_of.price", type: "object[]", optional: true },
      { name: "component_of.price.base", type: "float[]", optional: true },
      { name: "component_of.price.replacement", type: "float[]", optional: true },
      { name: "component_of.price.coa_revenue", type: "string[]", facet: true, optional: true },
      { name: "component_of.price.tax_profile", type: "string[]", optional: true },
      { name: "component_of.price.formula", type: "string[]", facet: true, optional: true },
      { name: "component_of.price.discountable", type: "bool[]", facet: true, optional: true },
      { name: "crms_stock_level_ids", type: "int64[]", optional: true },
      { name: "images", type: "string[]", optional: true },
      { name: "updated_by", type: "string", facet: false, optional: true },
      { name: "updated_at", type: "int64", sort: true, index: true, facet: false },
      { name: "created_at", type: "int64", sort: true, index: true, facet: false, optional: true },
    ],
    default_sorting_field: "name",
  },
  displayDefaults: {
    columns: ["type", "name", "tags.name", "components.name"],
    filters: { type: ["rental", "sale", "service"], active: [true] },
    sort: { column: "name", direction: "asc" },
    group: null,
    facet: [],
  },
};
