import type { TypesenseCollectionConfig } from "./types.ts";

export const webshopProducts: TypesenseCollectionConfig = {
  alias: "webshop-products",
  version: 4,
  firestoreCollection: "webshop-products",
  collectionName: "webshop-products_v4",
  schema: {
    name: "webshop-products_v4",
    enable_nested_fields: true,
    fields: [
      { name: "uid", type: "string", sort: true, facet: false },
      { name: "name", type: "string", sort: true, stem: true, facet: false },
      { name: "type", type: "string", facet: true, sort: true, stem: true },
      { name: "stock_method", type: "string", facet: true, sort: true, stem: true, optional: true },
      { name: "active", type: "bool", sort: true, facet: true },
      { name: "component_only", type: "bool", sort: true, facet: true, optional: true },
      { name: "eligible_delivery", type: "bool", sort: true, facet: true, optional: true },
      { name: "eligible_in_store_pickup", type: "bool", sort: true, facet: true, optional: true },
      { name: "eligible_shipping_ground", type: "bool", sort: true, facet: true, optional: true },
      { name: "eligible_shipping_air", type: "bool", sort: true, facet: true, optional: true },
      { name: "price", type: "object" },
      { name: "price.base", type: "float", optional: true },
      { name: "price.replacement", type: "float", optional: true },
      { name: "price.taxes", type: "object[]", optional: true },
      { name: "price.taxes.uid", type: "string[]", facet: true, optional: true },
      { name: "price.taxes.name", type: "string[]", optional: true },
      { name: "price.taxes.rate", type: "float[]", optional: true },
      { name: "price.taxes.type", type: "string[]", optional: true },
      { name: "price.formula", type: "string", facet: true, optional: true },
      { name: "price.discountable", type: "bool", facet: true, optional: true },
      { name: "webshop", type: "object" },
      { name: "webshop.available", type: "bool", facet: true },
      { name: "webshop.description", type: "string", optional: true },
      { name: "alternates", type: "object[]", optional: true },
      { name: "alternates.uid", type: "string[]", facet: false, optional: true },
      { name: "alternates.name", type: "string[]", stem: true, optional: true },
      { name: "alternates.description", type: "string[]", optional: true },
      { name: "shipping", type: "object", optional: true },
      { name: "shipping.weight", type: "int32", optional: true },
      { name: "shipping.height", type: "int32", optional: true },
      { name: "shipping.width", type: "int32", optional: true },
      { name: "shipping.length", type: "int32", optional: true },
      { name: "shipping.air_hazardous", type: "bool", facet: true, optional: true },
      { name: "shipping.air_un", type: "int32", optional: true },
      { name: "tags", type: "object[]", optional: true },
      { name: "tags.uid", type: "string[]", facet: false, optional: true },
      { name: "tags.name", type: "string[]", stem: true, facet: false, optional: true },
      { name: "components", type: "object[]", optional: true },
      { name: "components.uid", type: "string[]", optional: true },
      { name: "components.name", type: "string[]", optional: true },
      { name: "components.quantity", type: "float[]", optional: true },
      { name: "components.active", type: "bool[]", facet: true, optional: true },
      { name: "components.description", type: "string[]", optional: true },
      { name: "components.inclusion_type", type: "string[]", facet: true, optional: true },
      { name: "components.type", type: "string[]", facet: true, optional: true },
      { name: "components.zero_priced", type: "bool[]", facet: true, optional: true },
      { name: "components.price", type: "object[]", optional: true },
      { name: "components.price.base", type: "float[]", optional: true },
      { name: "components.price.replacement", type: "float[]", optional: true },
      { name: "components.price.taxes", type: "object[]", optional: true },
      { name: "components.price.taxes.uid", type: "string[]", optional: true },
      { name: "components.price.taxes.name", type: "string[]", optional: true },
      { name: "components.price.formula", type: "string[]", facet: true, optional: true },
      { name: "components.price.discountable", type: "bool[]", facet: true, optional: true },
      { name: "component_of", type: "object[]", optional: true },
      { name: "component_of.uid", type: "string[]", optional: true },
      { name: "component_of.name", type: "string[]", optional: true },
      { name: "component_of.quantity", type: "float[]", optional: true },
      { name: "component_of.active", type: "bool[]", facet: true, optional: true },
      { name: "component_of.description", type: "string[]", optional: true },
      { name: "component_of.inclusion_type", type: "string[]", facet: true, optional: true },
      { name: "component_of.type", type: "string[]", facet: true, optional: true },
      { name: "component_of.zero_priced", type: "bool[]", facet: true, optional: true },
      { name: "component_of.price", type: "object[]", optional: true },
      { name: "component_of.price.base", type: "float[]", optional: true },
      { name: "component_of.price.replacement", type: "float[]", optional: true },
      { name: "component_of.price.taxes", type: "object[]", optional: true },
      { name: "component_of.price.taxes.uid", type: "string[]", optional: true },
      { name: "component_of.price.taxes.name", type: "string[]", optional: true },
      { name: "component_of.price.formula", type: "string[]", facet: true, optional: true },
      { name: "component_of.price.discountable", type: "bool[]", facet: true, optional: true },
      { name: "updated_at", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "created_at", type: "int64", sort: true, index: true, facet: false, optional: true },
    ],
    default_sorting_field: "name",
  },
  synonyms: [],
  displayDefaults: {
    columns: ["name", "type", "active"],
    filters: {},
    sort: { column: "name", direction: "asc" },
    group: null,
    facet: [],
  },
};
