/**
 * Order propagation rules — create-order and update-order transactions.
 *
 * Traced from: api-cloudrun/src/services/orders.ts
 */
import type { CollectionRule, TransactionDefinition } from "./types.ts";

// ── create-order ─────────────────────────────────────────────────

export const createOrderRules: CollectionRule[] = [
  {
    id: "create-order:org-to-order",
    source: "organizations",
    target: "orders",
    mode: "embed",
    invariant: "Orders carry a denormalized org snapshot so the UI never needs a join to display org name/billing",
    transaction: "create-order",
    fields: [
      { source: "uid", target: "organization.uid" },
      { source: "name", target: "organization.name" },
      { source: "crms_id", target: "organization.crms_id" },
      { source: "xero_id", target: "organization.xero_id" },
      { source: "billing_address", target: "organization.billing_address" },
    ],
  },
  {
    id: "create-order:products-to-order-items",
    source: "products",
    target: "orders",
    mode: "embed",
    invariant: "Line items inherit product type, stock_method, and default price from the product catalog",
    transaction: "create-order",
    fields: [
      { source: "type", target: "items[].type" },
      { source: "stock_method", target: "items[].stock_method" },
      { source: "price.base", target: "items[].price.base", transform: "fallback — used only when input omits price" },
      { source: "price.tax_profile", target: "items[].price.tax_profile", transform: "fallback — used only when input omits price" },
      { source: "name", target: "items[].name", transform: "fallback — input name takes precedence" },
    ],
  },
  {
    id: "create-order:order-self-derive",
    source: "orders",
    target: "orders",
    mode: "derive",
    invariant: "Totals, query arrays, and order number are computed server-side to prevent client tampering",
    transaction: "create-order",
    fields: [
      { source: "items[]", target: "totals", transform: "calculateOrderTotals(items) → {subtotal, tax_amount, discount_amount, total, taxes}" },
      { source: "items[]", target: "query_by_items", transform: "consolidateItems(items) → product uids for search" },
      { source: "destinations[].*.contact.uid", target: "query_by_contacts", transform: "flatten all contact uids from delivery/collection endpoints" },
      { source: "counters/orders.count", target: "number", transform: "atomic increment of orders counter" },
      { source: "dates.*", target: "dates.*_fs", transform: "Timestamp.fromDate() — each ISO string gets a Firestore timestamp companion" },
    ],
  },
  {
    id: "create-order:order-to-bookings",
    source: "orders",
    target: "bookings",
    mode: "co-write",
    invariant: "One booking per consolidated product per destination — tracks per-product stock lifecycle",
    transaction: "create-order",
    fields: [
      { source: "uid", target: "uid_order" },
      { source: "number", target: "number" },
      { source: "status", target: "status" },
      { source: "subject", target: "subject" },
      { source: "organization.uid", target: "organization.uid" },
      { source: "organization.name", target: "organization.name" },
      { source: "organization.crms_id", target: "organization.crms_id" },
      { source: "destinations[].delivery.uid", target: "uid_destination_delivery" },
      { source: "destinations[].delivery.uid", target: "destinations.delivery.uid" },
      { source: "destinations[].delivery.address", target: "destinations.delivery.address" },
      { source: "destinations[].collection.uid", target: "uid_destination_collection" },
      { source: "destinations[].collection.uid", target: "destinations.collection.uid" },
      { source: "destinations[].collection.address", target: "destinations.collection.address" },
      { source: "dates", target: "dates", transform: "buildBookingDates — rental: delivery_start→start, collection_start→end; sale: delivery_start→start, end=null" },
      { source: "items[].uid", target: "uid_product", transform: "consolidated item uid (the product uid)" },
      { source: "items[].name", target: "name", transform: "from consolidated item" },
      { source: "items[].quantity", target: "quantity", transform: "sum of duplicate line items via consolidateItems()" },
      { source: "items[].type", target: "type", transform: "from consolidated item" },
      { source: "items[].price.total", target: "total_price", transform: "sum across consolidated duplicates" },
      { source: "items[].price.total", target: "unit_price", transform: "total_price / quantity" },
      { source: "status + type + quantity", target: "breakdown", transform: "calculateBreakdown() — distributes quantity into status buckets (quoted/reserved/prepped/out/returned/lost/damaged)" },
    ],
  },
  {
    id: "create-order:ledger-to-bookings",
    source: "inventory-ledgers",
    target: "bookings",
    mode: "embed",
    invariant: "Bookings get store allocation from the inventory ledger to track where stock is drawn from",
    transaction: "create-order",
    fields: [
      { source: "store_breakdown", target: "stores", transform: "allocateBookingToStores() — draws quantity from default store first, then alphabetical" },
      { source: "store_breakdown", target: "query_by_uid_store", transform: "allocated store uids for search" },
      { source: "store_breakdown", target: "shortage", transform: "remaining quantity that couldn't be allocated" },
    ],
  },
  {
    id: "create-order:bookings-to-stock-summaries",
    source: "bookings",
    target: "stock-summaries",
    mode: "co-write",
    invariant: "Stock summaries aggregate all bookings for a product/date-range so availability is queryable without scanning bookings",
    transaction: "create-order",
    fields: [
      { source: "(booking document)", target: "bookings[]", transform: "full booking embedded in array — one summary per product per date range" },
      { source: "breakdown", target: "bookings_breakdown", transform: "sum of all booking breakdowns in this date range" },
      { source: "breakdown", target: "quantity_booked", transform: "reserved + prepped + out across all bookings" },
      { source: "breakdown", target: "quantity_available", transform: "quantity_held - quantity_booked - quantity_out_of_service" },
    ],
  },
  {
    id: "create-order:ledger-to-stock-summaries",
    source: "inventory-ledgers",
    target: "stock-summaries",
    mode: "embed",
    invariant: "Stock summaries carry inventory totals from the ledger so availability can be computed in one read",
    transaction: "create-order",
    fields: [
      { source: "uid", target: "uid_product" },
      { source: "type", target: "type" },
      { source: "quantity_held", target: "quantity_held" },
      { source: "quantity_in_service", target: "quantity_in_service" },
      { source: "quantity_out_of_service", target: "quantity_out_of_service" },
      { source: "store_breakdown", target: "store_breakdown" },
      { source: "store_breakdown[].uid_store", target: "query_by_uid_store" },
    ],
  },
  {
    id: "create-order:stock-to-public-stock",
    source: "stock-summaries",
    target: "public-stock-summaries",
    mode: "derive",
    invariant: "Public stock summaries strip internal details (bookings, breakdowns) for webshop availability queries",
    transaction: "create-order",
    fields: [
      { source: "uid", target: "uid" },
      { source: "uid_product", target: "uid_product" },
      { source: "type", target: "type" },
      { source: "summary_type", target: "summary_type" },
      { source: "dates", target: "dates" },
      { source: "quantity_available", target: "quantity_available" },
      { source: "store_breakdown", target: "store_breakdown", transform: "simplified to {uid_store, quantity} only — strips locations, name, default, crms_stock_level_id" },
      { source: "query_by_uid_store", target: "query_by_uid_store" },
    ],
  },
];

export const createOrderTransaction: TransactionDefinition = {
  id: "create-order",
  description: "Creates an order with bookings and stock summaries in a single Firestore transaction. Skips bookings for draft/canceled status.",
  steps: [
    "create-order:org-to-order",
    "create-order:products-to-order-items",
    "create-order:order-self-derive",
    "create-order:order-to-bookings",
    "create-order:ledger-to-bookings",
    "create-order:bookings-to-stock-summaries",
    "create-order:ledger-to-stock-summaries",
    "create-order:stock-to-public-stock",
  ],
};

// ── update-order ─────────────────────────────────────────────────

export const updateOrderRules: CollectionRule[] = [
  {
    id: "update-order:org-to-order",
    source: "organizations",
    target: "orders",
    mode: "embed",
    invariant: "When the order's org reference changes, fetch fresh org data to keep the denormalized snapshot current",
    transaction: "update-order",
    fields: [
      { source: "uid", target: "organization.uid" },
      { source: "name", target: "organization.name" },
      { source: "crms_id", target: "organization.crms_id" },
      { source: "xero_id", target: "organization.xero_id" },
      { source: "billing_address", target: "organization.billing_address" },
    ],
  },
  {
    id: "update-order:order-self-derive",
    source: "orders",
    target: "orders",
    mode: "derive",
    invariant: "Totals, query arrays, and date timestamps recomputed on every update",
    transaction: "update-order",
    fields: [
      { source: "items[]", target: "totals", transform: "calculateOrderTotals(items)" },
      { source: "items[]", target: "query_by_items", transform: "consolidateItems(items) → product uids" },
      { source: "destinations[].*.contact.uid", target: "query_by_contacts", transform: "flatten contact uids" },
      { source: "dates.*", target: "dates.*_fs", transform: "Timestamp.fromDate() for each date field" },
    ],
  },
  {
    id: "update-order:order-to-bookings",
    source: "orders",
    target: "bookings",
    mode: "co-write",
    invariant: "Bookings are diffed — created, updated, or deleted based on item/status/date changes",
    transaction: "update-order",
    fields: [
      { source: "uid", target: "uid_order" },
      { source: "number", target: "number" },
      { source: "status", target: "status" },
      { source: "subject", target: "subject" },
      { source: "organization.{uid,name,crms_id}", target: "organization.{uid,name,crms_id}" },
      { source: "destinations[].delivery", target: "destinations.delivery", transform: "{uid, address}" },
      { source: "destinations[].collection", target: "destinations.collection", transform: "{uid, address}" },
      { source: "dates", target: "dates", transform: "buildBookingDates — same logic as create" },
      { source: "items[]", target: "(booking fields)", transform: "consolidated items → uid_product, name, quantity, type, total_price, unit_price" },
      { source: "status + type + quantity", target: "breakdown", transform: "calculateBreakdown() — preserves existing prepped/out/returned/lost/damaged counts" },
    ],
  },
  {
    id: "update-order:ledger-to-bookings",
    source: "inventory-ledgers",
    target: "bookings",
    mode: "embed",
    invariant: "Store allocation re-read from ledger on every booking update",
    transaction: "update-order",
    fields: [
      { source: "store_breakdown", target: "stores", transform: "allocateBookingToStores() — only for part-prepped/prepped/active status" },
      { source: "store_breakdown", target: "query_by_uid_store" },
      { source: "store_breakdown", target: "shortage" },
    ],
  },
  {
    id: "update-order:bookings-to-stock-summaries",
    source: "bookings",
    target: "stock-summaries",
    mode: "co-write",
    invariant: "All stock summaries for affected products are recalculated — both for updated and removed bookings",
    transaction: "update-order",
    fields: [
      { source: "(booking document)", target: "bookings[]", transform: "full booking embedded; removed bookings get zero breakdown" },
      { source: "breakdown", target: "bookings_breakdown" },
      { source: "breakdown", target: "quantity_booked" },
      { source: "breakdown", target: "quantity_available" },
    ],
  },
  {
    id: "update-order:stock-to-public-stock",
    source: "stock-summaries",
    target: "public-stock-summaries",
    mode: "derive",
    invariant: "Public stock summaries mirror internal summaries with simplified store breakdown",
    transaction: "update-order",
    fields: [
      { source: "*", target: "*", transform: "same as create-order — copies all fields, simplifies store_breakdown to {uid_store, quantity}" },
    ],
  },
];

export const updateOrderTransaction: TransactionDefinition = {
  id: "update-order",
  description: "Updates an order, diffing items/status/dates to create/update/delete bookings and recalculate stock summaries.",
  steps: [
    "update-order:org-to-order",
    "update-order:order-self-derive",
    "update-order:order-to-bookings",
    "update-order:ledger-to-bookings",
    "update-order:bookings-to-stock-summaries",
    "update-order:stock-to-public-stock",
  ],
};
