/**
 * Order propagation rules — create-order and update-order transactions.
 *
 * Traced from: api-cloudrun/src/services/orders.ts
 */
import type { CollectionRule, TransactionDefinition } from "./types.ts";

// ── create-order ─────────────────────────────────────────────────

export const createOrderRules: CollectionRule[] = [
  {
    id: "create-order:org-to-order",
    source: "organizations",
    target: "orders",
    mode: "embed",
    invariant: "Orders carry a denormalized org snapshot so the UI never needs a join to display org name/billing",
    transaction: "create-order",
    fields: [
      { source: ["uid"], target: ["organization", "uid"] },
      { source: ["name"], target: ["organization", "name"] },
      { source: ["crms_id"], target: ["organization", "crms_id"] },
      { source: ["xero_id"], target: ["organization", "xero_id"] },
      { source: ["billing_address"], target: ["organization", "billing_address"] },
    ],
  },
  {
    id: "create-order:products-to-order-items",
    source: "products",
    target: "orders",
    mode: "embed",
    invariant: "Line items inherit product type, stock_method, and default price from the product catalog",
    transaction: "create-order",
    fields: [
      { source: ["type"], target: ["items", "type"] },
      { source: ["stock_method"], target: ["items", "stock_method"] },
      { source: ["price", "base"], target: ["items", "price", "base"], transform: "fallback — used only when input omits price" },
      { source: ["price", "replacement"], target: ["items", "price", "replacement"], transform: "fallback — used only when input omits replacement" },
      { source: ["price", "taxes"], target: ["items", "price", "taxes"], transform: "fallback — denormalized TaxRef[] from product catalog, used when input omits taxes" },
      { source: ["name"], target: ["items", "name"], transform: "fallback — input name takes precedence" },
    ],
  },
  {
    id: "create-order:order-self-derive",
    source: "orders",
    target: "orders",
    mode: "derive",
    invariant: "Totals, query arrays, and order number are computed server-side to prevent client tampering",
    transaction: "create-order",
    fields: [
      { source: ["items"], target: ["totals"], transform: "calculateOrderTotals(items, taxes) → {subtotal, subtotal_discounted, discount_amount, taxes, transaction_fees, total}. Two-pass: computes pre-tax items first, then transaction fees from subtotal_discounted. transaction_fee items excluded from bookings/stock." },
      { source: ["items"], target: ["query_by_items"], transform: "consolidateItems(items) → product uids for search" },
      { source: ["destinations"], target: ["query_by_contacts"], transform: "flatten all contact uids from delivery/collection endpoints" },
      { source: [], target: ["number"], transform: "atomic increment of counters/orders.count" },
      { source: ["dates"], target: ["dates"], transform: "Timestamp.fromDate() — each ISO string gets a Firestore timestamp companion (*_fs)" },
    ],
  },
  {
    id: "create-order:order-to-bookings",
    source: "orders",
    target: "bookings",
    mode: "co-write",
    invariant: "One booking per consolidated product per destination — tracks per-product stock lifecycle",
    transaction: "create-order",
    fields: [
      { source: ["uid"], target: ["uid_order"] },
      { source: ["number"], target: ["number"] },
      { source: ["status"], target: ["status"] },
      { source: ["subject"], target: ["subject"] },
      { source: ["organization", "uid"], target: ["organization", "uid"] },
      { source: ["organization", "name"], target: ["organization", "name"] },
      { source: ["organization", "crms_id"], target: ["organization", "crms_id"] },
      { source: ["destinations", "delivery", "uid"], target: ["uid_destination_delivery"] },
      { source: ["destinations", "delivery", "uid"], target: ["destinations", "delivery", "uid"] },
      { source: ["destinations", "delivery", "address"], target: ["destinations", "delivery", "address"] },
      { source: ["destinations", "collection", "uid"], target: ["uid_destination_collection"] },
      { source: ["destinations", "collection", "uid"], target: ["destinations", "collection", "uid"] },
      { source: ["destinations", "collection", "address"], target: ["destinations", "collection", "address"] },
      { source: ["dates"], target: ["dates"], transform: "buildBookingDates — rental: delivery_start→start, collection_start→end; sale: delivery_start→start, end=null" },
      { source: ["items", "uid"], target: ["uid_product"], transform: "consolidated item uid (the product uid)" },
      { source: ["items", "name"], target: ["name"], transform: "from consolidated item" },
      { source: ["items", "quantity"], target: ["quantity"], transform: "sum of duplicate line items via consolidateItems()" },
      { source: ["items", "type"], target: ["type"], transform: "from consolidated item" },
      { source: ["items", "price", "total"], target: ["total_price"], transform: "sum across consolidated duplicates" },
      { source: ["items", "price", "total"], target: ["unit_price"], transform: "total_price / quantity" },
      { source: [], target: ["breakdown"], transform: "calculateBreakdown(status, type, quantity) — distributes quantity into status buckets (quoted/reserved/prepped/out/returned/lost/damaged)" },
    ],
  },
  {
    id: "create-order:ledger-to-bookings",
    source: "inventory-ledgers",
    target: "bookings",
    mode: "embed",
    invariant: "Bookings get store allocation from the inventory ledger to track where stock is drawn from",
    transaction: "create-order",
    fields: [
      { source: ["store_breakdown"], target: ["stores"], transform: "allocateBookingToStores() — draws quantity from default store first, then alphabetical" },
      { source: ["store_breakdown"], target: ["query_by_uid_store"], transform: "allocated store uids for search" },
      { source: ["store_breakdown"], target: ["shortage"], transform: "remaining quantity that couldn't be allocated" },
    ],
  },
  {
    id: "create-order:bookings-to-stock-summaries",
    source: "bookings",
    target: "stock-summaries",
    mode: "co-write",
    invariant: "Stock summaries aggregate all bookings for a product/date-range so availability is queryable without scanning bookings",
    transaction: "create-order",
    fields: [
      { source: [], target: ["bookings"], transform: "full booking document embedded in array — one summary per product per date range" },
      { source: ["breakdown"], target: ["bookings_breakdown"], transform: "sum of all booking breakdowns in this date range" },
      { source: ["breakdown"], target: ["quantity_booked"], transform: "reserved + prepped + out across all bookings" },
      { source: ["breakdown"], target: ["quantity_available"], transform: "quantity_held - quantity_booked - quantity_out_of_service" },
    ],
  },
  {
    id: "create-order:ledger-to-stock-summaries",
    source: "inventory-ledgers",
    target: "stock-summaries",
    mode: "embed",
    invariant: "Stock summaries carry inventory totals from the ledger so availability can be computed in one read",
    transaction: "create-order",
    fields: [
      { source: ["uid"], target: ["uid_product"] },
      { source: ["type"], target: ["type"] },
      { source: ["quantity_held"], target: ["quantity_held"] },
      { source: ["quantity_in_service"], target: ["quantity_in_service"] },
      { source: ["quantity_out_of_service"], target: ["quantity_out_of_service"] },
      { source: ["store_breakdown"], target: ["store_breakdown"] },
      { source: ["store_breakdown", "uid_store"], target: ["query_by_uid_store"] },
    ],
  },
  {
    id: "create-order:stock-to-public-stock",
    source: "stock-summaries",
    target: "public-stock-summaries",
    mode: "derive",
    invariant: "Public stock summaries strip internal details (bookings, breakdowns) for webshop availability queries",
    transaction: "create-order",
    fields: [
      { source: ["uid"], target: ["uid"] },
      { source: ["uid_product"], target: ["uid_product"] },
      { source: ["type"], target: ["type"] },
      { source: ["summary_type"], target: ["summary_type"] },
      { source: ["dates"], target: ["dates"] },
      { source: ["quantity_available"], target: ["quantity_available"] },
      { source: ["store_breakdown"], target: ["store_breakdown"], transform: "simplified to {uid_store, quantity} only — strips locations, name, default, crms_stock_level_id" },
      { source: ["query_by_uid_store"], target: ["query_by_uid_store"] },
    ],
  },
  {
    id: "create-order:order-to-order-events",
    source: "orders",
    target: "order-events",
    mode: "co-write",
    invariant: "Lightweight schedule projection — one event per destination per position for dashboard calendar/card views",
    transaction: "create-order",
    fields: [
      { source: ["uid"], target: ["uid_order"] },
      { source: ["number"], target: ["order_number"] },
      { source: ["status"], target: ["status"] },
      { source: ["subject"], target: ["subject"] },
      { source: ["organization", "uid"], target: ["organization", "uid"] },
      { source: ["organization", "name"], target: ["organization", "name"] },
      { source: ["destinations", "delivery"], target: ["destination"], transform: "full DocDestinationEndpointType for start events" },
      { source: ["destinations", "collection"], target: ["destination"], transform: "full DocDestinationEndpointType for end events" },
      { source: ["dates", "delivery_start"], target: ["date"], transform: "start event date" },
      { source: ["dates", "collection_start"], target: ["date"], transform: "end event date (rental items only)" },
      { source: ["items"], target: ["item_uids"], transform: "product UIDs filtered by destination — delivery types for start, collection types for end" },
      { source: ["customer_collecting", "customer_returning"], target: ["event_type"], transform: "getEventType(customerCollecting, customerReturning, position)" },
    ],
  },
  {
    id: "create-order:order-to-order-warehouse",
    source: "orders",
    target: "order-warehouses",
    mode: "co-write",
    invariant: "Warehouse clients see a sanitized order view — pricing, totals, invoices, tax profile, CRM/Xero ids, version, notes, and transaction_fee items are stripped",
    transaction: "create-order",
    fields: [
      { source: ["uid"], target: ["uid"] },
      { source: ["number"], target: ["number"] },
      { source: ["status"], target: ["status"] },
      { source: ["organization", "uid"], target: ["organization", "uid"] },
      { source: ["organization", "name"], target: ["organization", "name"] },
      { source: ["dates"], target: ["dates"] },
      { source: ["destinations"], target: ["destinations"], transform: "full DocDestination with contacts retained" },
      { source: ["items"], target: ["items"], transform: "strips price, inclusion_type, zero_priced, crms_id; drops transaction_fee items entirely" },
      { source: ["subject"], target: ["subject"] },
      { source: ["reference"], target: ["reference"] },
      { source: ["customer_collecting"], target: ["customer_collecting"] },
      { source: ["customer_returning"], target: ["customer_returning"] },
      { source: ["query_by_items"], target: ["query_by_items"] },
      { source: ["query_by_contacts"], target: ["query_by_contacts"] },
    ],
  },
];

export const createOrderTransaction: TransactionDefinition = {
  id: "create-order",
  description: "Creates an order with bookings, stock summaries, order events, and the sanitized warehouse view in a single Firestore transaction. Skips bookings/events for draft/canceled status. Cowrites default threads for the order and each order-event.",
  steps: [
    "create-order:org-to-order",
    "create-order:products-to-order-items",
    "create-order:order-self-derive",
    "create-order:order-to-bookings",
    "create-order:ledger-to-bookings",
    "create-order:bookings-to-stock-summaries",
    "create-order:ledger-to-stock-summaries",
    "create-order:stock-to-public-stock",
    "create-order:order-to-order-events",
    "create-order:order-to-order-warehouse",
    "cowrite-thread:orders-to-thread",
    "cowrite-thread:thread-to-orders",
    "cowrite-thread:order-events-to-thread",
    "cowrite-thread:thread-to-order-events",
  ],
};

// ── update-order ─────────────────────────────────────────────────

export const updateOrderRules: CollectionRule[] = [
  {
    id: "update-order:org-to-order",
    source: "organizations",
    target: "orders",
    mode: "embed",
    invariant: "When the order's org reference changes, fetch fresh org data to keep the denormalized snapshot current",
    transaction: "update-order",
    fields: [
      { source: ["uid"], target: ["organization", "uid"] },
      { source: ["name"], target: ["organization", "name"] },
      { source: ["crms_id"], target: ["organization", "crms_id"] },
      { source: ["xero_id"], target: ["organization", "xero_id"] },
      { source: ["billing_address"], target: ["organization", "billing_address"] },
    ],
  },
  {
    id: "update-order:order-self-derive",
    source: "orders",
    target: "orders",
    mode: "derive",
    invariant: "Totals, query arrays, and date timestamps recomputed on every update",
    transaction: "update-order",
    fields: [
      { source: ["items"], target: ["totals"], transform: "calculateOrderTotals(items, taxes) → {subtotal, subtotal_discounted, discount_amount, taxes, transaction_fees, total}" },
      { source: ["items"], target: ["query_by_items"], transform: "consolidateItems(items) → product uids" },
      { source: ["destinations"], target: ["query_by_contacts"], transform: "flatten contact uids" },
      { source: ["dates"], target: ["dates"], transform: "Timestamp.fromDate() for each date field" },
    ],
  },
  {
    id: "update-order:order-to-bookings",
    source: "orders",
    target: "bookings",
    mode: "co-write",
    invariant: "Bookings are diffed — created, updated, or deleted based on item/status/date/destination changes. Orphan bookings (bookings whose {order,product,destination} composite id no longer appears in the order) are deleted and their stock summaries zeroed.",
    transaction: "update-order",
    fields: [
      { source: ["uid"], target: ["uid_order"] },
      { source: ["number"], target: ["number"] },
      { source: ["status"], target: ["status"] },
      { source: ["subject"], target: ["subject"] },
      { source: ["organization", "uid"], target: ["organization", "uid"] },
      { source: ["organization", "name"], target: ["organization", "name"] },
      { source: ["organization", "crms_id"], target: ["organization", "crms_id"] },
      { source: ["destinations", "delivery"], target: ["destinations", "delivery"], transform: "{uid, address}" },
      { source: ["destinations", "collection"], target: ["destinations", "collection"], transform: "{uid, address}" },
      { source: ["dates"], target: ["dates"], transform: "buildBookingDates — same logic as create" },
      { source: ["items"], target: [], transform: "consolidated items → uid_product, name, quantity, type, total_price, unit_price" },
      { source: [], target: ["breakdown"], transform: "calculateBreakdown(status, type, quantity) — preserves existing prepped/out/returned/lost/damaged counts" },
    ],
  },
  {
    id: "update-order:ledger-to-bookings",
    source: "inventory-ledgers",
    target: "bookings",
    mode: "embed",
    invariant: "Store allocation re-read from ledger on every booking update",
    transaction: "update-order",
    fields: [
      { source: ["store_breakdown"], target: ["stores"], transform: "allocateBookingToStores() — only for part-prepped/prepped/active status" },
      { source: ["store_breakdown"], target: ["query_by_uid_store"] },
      { source: ["store_breakdown"], target: ["shortage"] },
    ],
  },
  {
    id: "update-order:bookings-to-stock-summaries",
    source: "bookings",
    target: "stock-summaries",
    mode: "co-write",
    invariant: "All stock summaries for affected products are recalculated — both for updated and removed bookings",
    transaction: "update-order",
    fields: [
      { source: [], target: ["bookings"], transform: "full booking document embedded; removed bookings get zero breakdown" },
      { source: ["breakdown"], target: ["bookings_breakdown"] },
      { source: ["breakdown"], target: ["quantity_booked"] },
      { source: ["breakdown"], target: ["quantity_available"] },
    ],
  },
  {
    id: "update-order:stock-to-public-stock",
    source: "stock-summaries",
    target: "public-stock-summaries",
    mode: "derive",
    invariant: "Public stock summaries mirror internal summaries with simplified store breakdown",
    transaction: "update-order",
    fields: [
      { source: [], target: [], transform: "same as create-order — copies all fields, simplifies store_breakdown to {uid_store, quantity}" },
    ],
  },
  {
    id: "update-order:order-to-order-events",
    source: "orders",
    target: "order-events",
    mode: "co-write",
    invariant: "Order events rebuilt on every update — old events for removed destinations are deleted",
    transaction: "update-order",
    fields: [
      { source: ["uid"], target: ["uid_order"] },
      { source: ["number"], target: ["order_number"] },
      { source: ["status"], target: ["status"] },
      { source: ["subject"], target: ["subject"] },
      { source: ["organization", "uid"], target: ["organization", "uid"] },
      { source: ["organization", "name"], target: ["organization", "name"] },
      { source: ["destinations", "delivery"], target: ["destination"], transform: "full DocDestinationEndpointType for start events" },
      { source: ["destinations", "collection"], target: ["destination"], transform: "full DocDestinationEndpointType for end events" },
      { source: ["dates", "delivery_start"], target: ["date"], transform: "start event date" },
      { source: ["dates", "collection_start"], target: ["date"], transform: "end event date (rental items only)" },
      { source: ["items"], target: ["item_uids"], transform: "product UIDs filtered by destination — delivery types for start, collection types for end" },
      { source: ["customer_collecting", "customer_returning"], target: ["event_type"], transform: "getEventType(customerCollecting, customerReturning, position)" },
    ],
  },
  {
    id: "update-order:order-to-order-warehouse",
    source: "orders",
    target: "order-warehouses",
    mode: "co-write",
    invariant: "Warehouse view mirrors the order on every update — stripped of pricing, totals, invoices, tax profile, CRM/Xero ids, version, notes, and transaction_fee items",
    transaction: "update-order",
    fields: [
      { source: ["uid"], target: ["uid"] },
      { source: ["number"], target: ["number"] },
      { source: ["status"], target: ["status"] },
      { source: ["organization", "uid"], target: ["organization", "uid"] },
      { source: ["organization", "name"], target: ["organization", "name"] },
      { source: ["dates"], target: ["dates"] },
      { source: ["destinations"], target: ["destinations"], transform: "full DocDestination with contacts retained" },
      { source: ["items"], target: ["items"], transform: "strips price, inclusion_type, zero_priced, crms_id; drops transaction_fee items entirely" },
      { source: ["subject"], target: ["subject"] },
      { source: ["reference"], target: ["reference"] },
      { source: ["customer_collecting"], target: ["customer_collecting"] },
      { source: ["customer_returning"], target: ["customer_returning"] },
      { source: ["query_by_items"], target: ["query_by_items"] },
      { source: ["query_by_contacts"], target: ["query_by_contacts"] },
    ],
  },
];

export const updateOrderTransaction: TransactionDefinition = {
  id: "update-order",
  description: "Updates an order, diffing items/status/dates to create/update/delete bookings, recalculate stock summaries, rebuild order events, and refresh the warehouse view.",
  steps: [
    "update-order:org-to-order",
    "update-order:order-self-derive",
    "update-order:order-to-bookings",
    "update-order:ledger-to-bookings",
    "update-order:bookings-to-stock-summaries",
    "update-order:stock-to-public-stock",
    "update-order:order-to-order-events",
    "update-order:order-to-order-warehouse",
    "update-order:items-to-invoices",
    "update-order:status-to-invoices",
  ],
};
